
# Site settings
title: Hacks, Tricks, and Discovery
email: hisma.mulya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I occasionally write about what I found interesting. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mamaz.github.com" # the base hostname & protocol for your site
twitter_username: hismamaz
github_username:  mamaz
future: true
gems:
    - jekyll-sitemap

# Build settings

#permalinks
permalink: none

#syntax-highlighting
highlighter: rouge
markdown: kramdown
