
# Site settings
title: I learn and write things
email: hisma.mulya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I occasionally write about what I found interesting. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mamaz.github.com" # the base hostname & protocol for your site
author: mamaz
twitter_username: hismamaz
github_username:  mamaz
future: true
gems:
    - jekyll-sitemap
    - jekyll-seo-tag
disqus_shortname: mamazblog
# Build settings

#permalinks
permalink: none

#syntax-highlighting
highlighter: rouge
markdown: kramdown

theme: jekyll-theme-minimal